version: '3.3'
services:
  web:
    image: php:8.2-fpm
    container_name: php8.2-nginx
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  db:
    image: postgres
    container_name: database
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./mysql:/var/lib/mysql